site_name: Leverege Stack Documentation
copyright: Copyright &copy; Leverege LLC 2022 | All Rights Reserved | IoT Changes Everything&trade;
theme:
  logo : assets/amplify-logo.svg
  favicon : assets/amplify-favicon.svg
  name: material
  custom_dir: overrides
  font:
    text: Inter
  features:
    - navigation.tabs
    - navigation.top
    - NOnavigation.sections
    - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
nav : 
  - Home: index.md
  - Project Setup:
     - architecture/index.md
     - Core Concepts:
        - architecture/core/index.md
     - Blueprints:
       - architecture/blueprint/index.md
       - Relationships: architecture/blueprint/relationship.md
     - Networks:
       - architecture/network/index.md
     - Systems & Devices:
       - architecture/system/index.md
     - Roles & Permissions:
       - architecture/roles/index.md
       - Permissions: architecture/roles/permission.md
       - Creating Roles: architecture/roles/role.md
  - UI Setup:
    - setup/index.md
    - Branding & Styling:
       - setup/branding/index.md
       - UI Theme: setup/branding/builder.md
       - UI Inspector: setup/branding/inspector.md
       - Logos: setup/branding/logos.md
       - Icons: setup/branding/icons.md
       - Email & SMS Templates: setup/branding/notifications.md
       - Empty States: setup/branding/empty-states.md
    - Navigation:
      - Roots: setup/nav/route.md
      - Sort & Order Pages: setup/nav/sort.md
      - Page Display Options: setup/nav/page.md
      - Styling Overrides : setup/nav/path-overrides.md
      - Role-Specific Settings: setup/nav/role.md
    - Developer Options:
      - Overview: setup/dev.md
  - UI Configuration:
     - config/index.md
     - Configuration Panels: config/config-basics.md
     - Layout Controller: config/layout-controller.md
     - Search: config/search-config.md
     - Map: config/map-config.md
     - Tables:
        - config/tables/table-viewer.md
        - config/tables/list-viewer.md
        - config/tables/responsive-table.md
        - config/tables/history-table-viewer.md
        - config/tables/history-list-viewer.md
        - config/tables/responsive-history-table.md
        - config/tables/parents.md
     - Aggregations Viewer: config/aggregations-viewer.md
     - Grouping Selector: config/grouping-selector.md
     - Rollovers and Selections: config/rollover-selection.md
     - Dashboard Viewer: config/dashboard-viewer.md
  - Features:
     - features/index.md
     - Account Access:
        - Two-Step Verification: features/account/authentication.md
        - One-Time Access Code: features/account/signincode.md
        - Multi-Role Management: features/account/roles.md
     - User Management:
        - features/users/index.md
     - Create & Edit Items:
        - features/create/index.md
     - Search & Filter Items:
        - features/search/index.md
        - Quick Search: features/search/quicksearch.md
     - Pairing:
        - features/pair/index.md
     - FOTA Management:
        - features/fota/index.md
        - Device Type: features/fota/type.md
        - Applications & Components: features/fota/application.md
        - FOTA Releases: features/fota/release.md
extra:
  version: 
    provider: mike
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/feed/update/urn:li:activity:6589859965832347648/
      name: Leverege on LinkedIn
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/leverege/
      name: Leverege on Facebook
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/leverege?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor
      name: Leverege on Twitter
extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - awesome-pages
  - mkdocs-video

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist
  - pymdownx.tilde
  - lightgallery
