site_name: Leverege Supervise & Amplify
copyright: Copyright &copy; Leverege LLC 2022 | All Rights Reserved | IoT Changes Everything&trade;
theme:
  logo : assets/amplify-logo.svg
  favicon : assets/amplify-favicon.svg
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.top
    - NOnavigation.sections
    - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
nav : 
  - Home: index.md
  - Introduction:
  - UI Setup:
    - Branding:
        - setup/branding/branding.md
    - Styling:
      - setup/configs/index.md
      - Icons: setup/configs/icons.md
    - Configuration:
      - setup/models/index.md
      - Model Util: setup/models/model-util.md
      - Editors: setup/models/editors.md
extra:
  version: 
    provider: mike
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/feed/update/urn:li:activity:6589859965832347648/
      name: Leverege on LinkedIn
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/leverege/
      name: Leverege on Facebook
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/leverege?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor
      name: Leverege on Twitter
extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - awesome-pages

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist
  - pymdownx.tilde
